### ISSUE TITLE
[Bug] Teleportor won't engage when RF requirement is 0 and internal RF is 0.

### ISSUE THREAD

**Issue by ghost** [thebrightspark/StructuralRelocation#2]
When the config is set such that the RF requirement for teleportation is 0, the teleportors still won't function if it has no RF in its internal buffer.

**Comment by thebrightspark** [comment]
Sorry for only getting to this now, but I just tested and this works fine. I changed the following settings:
```
D:energyAcrossDimensionsMultiplier=1.0
I:energyPerBlockBase=0
D:energyPerDistanceMultiplier=0.0
```
